"""empty message

Revision ID: 237d75c62ae4
Revises: 
Create Date: 2019-04-02 14:36:22.178443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237d75c62ae4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('ogrn', sa.String(length=20), nullable=True),
    sa.Column('kpp', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('activate', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subdivisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('ogrn', sa.String(length=20), nullable=True),
    sa.Column('kpp', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=255), nullable=True),
    sa.Column('show_telephones_together', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('show_emails_together', sa.Boolean(), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['organization'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['status'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=25), nullable=True),
    sa.Column('customer', sa.String(length=150), nullable=True),
    sa.Column('the_total_cost', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('organization', sa.Integer(), nullable=True),
    sa.Column('subdivision', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('patronymic', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('performer', sa.Boolean(), nullable=True),
    sa.Column('appraiser', sa.Boolean(), nullable=True),
    sa.Column('signer', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('controler', sa.Boolean(), nullable=True),
    sa.Column('can_see_all_documents', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['organization'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['subdivision'], ['subdivisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('appraisers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document', sa.Integer(), nullable=True),
    sa.Column('employee', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['employee'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('controlers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document', sa.Integer(), nullable=True),
    sa.Column('employee', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['employee'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('result', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document', sa.Integer(), nullable=True),
    sa.Column('employee', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['employee'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document', sa.Integer(), nullable=True),
    sa.Column('employee', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['employee'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('alias', sa.String(length=255), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('field_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['field_type'], ['field_types.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['template'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('alias', sa.String(length=255), nullable=True),
    sa.Column('template_field', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('field_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['field_type'], ['field_types.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['template_field'], ['template_fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_fields')
    op.drop_table('template_fields')
    op.drop_table('signers')
    op.drop_table('performers')
    op.drop_table('docs')
    op.drop_table('controlers')
    op.drop_table('appraisers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('groups')
    op.drop_table('documents')
    op.drop_table('templates')
    op.drop_table('subdivisions')
    op.drop_table('statuses')
    op.drop_table('organizations')
    op.drop_table('field_types')
    # ### end Alembic commands ###
