"""empty message

Revision ID: 543ddb6baffd
Revises: 1648e92146ec
Create Date: 2019-03-04 15:08:19.401665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543ddb6baffd'
down_revision = '1648e92146ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docs', sa.Column('filename', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'templates', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'template_id')
    op.drop_column('docs', 'filename')
    # ### end Alembic commands ###
