"""empty message

Revision ID: 5df1a6a8edd7
Revises: 3dcc5dc7d034
Create Date: 2019-03-20 10:35:51.736884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df1a6a8edd7'
down_revision = '3dcc5dc7d034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subdivisions', sa.Column('ogrn', sa.String(length=20), nullable=True))
    op.add_column('subdivisions', sa.Column('show_emails_together', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subdivisions', 'show_emails_together')
    op.drop_column('subdivisions', 'ogrn')
    # ### end Alembic commands ###
