"""empty message

Revision ID: 7db8169aaee5
Revises: eb5954fe4d0e
Create Date: 2019-03-21 09:29:05.682194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7db8169aaee5'
down_revision = 'eb5954fe4d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organization', sa.Integer(), nullable=True))
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['organization'], ['id'])
    op.drop_column('users', 'orgnization')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('orgnization', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_ibfk_1', 'users', 'organizations', ['orgnization'], ['id'])
    op.drop_column('users', 'organization')
    # ### end Alembic commands ###
