"""empty message

Revision ID: 8adafb33d10b
Revises: a1be1bd8836e
Create Date: 2019-03-19 11:18:31.110134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8adafb33d10b'
down_revision = 'a1be1bd8836e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_fields', sa.Column('value', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_fields', 'value')
    # ### end Alembic commands ###
