"""empty message

Revision ID: 8fcc403e21e8
Revises: 98c787683593
Create Date: 2019-03-20 10:33:50.433868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fcc403e21e8'
down_revision = '98c787683593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subdivisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('kpp', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=255), nullable=True),
    sa.Column('show_telephones_together', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subdivisions')
    # ### end Alembic commands ###
