"""empty message

Revision ID: 93921db83d67
Revises: 04685abf8e1b
Create Date: 2019-02-28 11:04:16.662180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93921db83d67'
down_revision = '04685abf8e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column('activate', sa.Boolean(), nullable=True))
    op.add_column('templates', sa.Column('file_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'file_path')
    op.drop_column('statuses', 'activate')
    # ### end Alembic commands ###
