"""empty message

Revision ID: a1be1bd8836e
Revises: cf3beafb708d
Create Date: 2019-03-06 16:09:51.786410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1be1bd8836e'
down_revision = 'cf3beafb708d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'groups', 'templates', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'template_id')
    # ### end Alembic commands ###
