"""empty message

Revision ID: c535433f1203
Revises: 7f38fe81c828
Create Date: 2019-02-28 10:27:05.903686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c535433f1203'
down_revision = '7f38fe81c828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_fields', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_fields', sa.Column('value', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
