"""empty message

Revision ID: cf3beafb708d
Revises: 543ddb6baffd
Create Date: 2019-03-06 15:44:51.295692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf3beafb708d'
down_revision = '543ddb6baffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('document_fields', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('document_fields', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'document_fields', 'groups', ['group_id'], ['id'])
    op.add_column('template_fields', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('template_fields', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'template_fields', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'template_fields', type_='foreignkey')
    op.drop_column('template_fields', 'group_id')
    op.drop_column('template_fields', 'comment')
    op.drop_constraint(None, 'document_fields', type_='foreignkey')
    op.drop_column('document_fields', 'group_id')
    op.drop_column('document_fields', 'comment')
    op.drop_table('groups')
    # ### end Alembic commands ###
