"""empty message

Revision ID: eb5954fe4d0e
Revises: 5df1a6a8edd7
Create Date: 2019-03-20 10:44:42.430562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb5954fe4d0e'
down_revision = '5df1a6a8edd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subdivision', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'subdivisions', ['subdivision'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'subdivision')
    # ### end Alembic commands ###
